export const actionTypes = {
  // USER
  SAVE_USER_LOGIN: "SAVE_USER_LOGIN",

  // FILM
  SAVE_FILM_LIST: "SAVE_FILM_LIST",
  SAVE_FILM_DETAIL: "SAVE_FILM_DETAIL",
  SAVE_FILM_SCHEDULE: "SAVE_FILM_SCHEDULE",

  // CINEMA
  SAVE_CINEMA_SYSTEM_LIST: "SAVE_CINEMA_SYSTEM_LIST",
  SAVE_CINEMA_LIST: "SAVE_CINEMA_LIST",

  // LANGUAGE
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  // TICKET
  BOOK_TICKET: "BOOK_TICKET",
};
