export const actionTypes = {
  // USER
  SAVE_USER_LOGIN: "SAVE_USER_LOGIN",

  // FILM
  SAVE_FILM_LIST: "SAVE_FILM_LIST",
  SAVE_FILM_DETAIL: "SAVE_FILM_DETAIL",

  // CINEMA
  SAVE_CINEMA_SYSTEM_LIST: "SAVE_CINEMA_SYSTEM_LIST",
  SAVE_CINEMA_LIST: "SAVE_CINEMA_LIST",
};
