export const actionTypes = {
  SAVE_USER_LOGIN: "SAVE_USER_LOGIN",
  SAVE_FILM_LIST: "SAVE_FILM_LIST",
  SAVE_FILM_DETAIL: "SAVE_FILM_DETAIL",

  // MODAL
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  OPEN_MODAL_CREATE_FILM: "OPEN_MODAL_CREATE_FILM",
  SET_HANDLE_OK_MODAL: "SET_HANDLE_OK_MODAL",
  OPEN_MODAL_EDIT_FILM: "OPEN_MODAL_EDIT_FILM",
  OPEN_MODAL_CREATE_USER: "OPEN_MODAL_CREATE_USER",
  OPEN_MODAL_EDIT_USER: "OPEN_MODAL_EDIT_USER",

  // CINEMA
  SAVE_CINEMA_SYSTEM_LIST: "SAVE_CINEMA_SYSTEM_LIST",
  SAVE_CINEMA_LIST: "SAVE_CINEMA_LIST",
  SAVE_CINEMA_SCHEDULE: "SAVE_CINEMA_SCHEDULE",

  // USER
  SAVE_USER_TYPE_LIST: "SAVE_USER_TYPE_LIST",
  SAVE_USER_LIST: "SAVE_USER_LIST",
  SAVE_USER_DETAIL: "SAVE_USER_DETAIL",
};
