export const sagaTypes = {
  // AUTH
  SIGN_IN_SAGA: "SIGN_IN_SAGA",
  GET_USER_LOGIN_SAGA: "GET_USER_LOGIN_SAGA",

  // FILM
  CREATE_FILM_SAGA: "CREATE_FILM_SAGA",
  GET_FILM_LIST_SAGA: "GET_FILM_LIST_SAGA",
  DELETE_FILM_SAGA: "DELETE_FILM_SAGA",
  GET_FILM_DETAIL_SAGA: "GET_FILM_DETAIL_SAGA",
  EDIT_FILM_SAGA: "EDIT_FILM_SAGA",

  // CINEMA
  GET_CINEMA_SYSTEM_LIST_SAGA: "GET_CINEMA_SYSTEM_LIST_SAGA",
  GET_CINEMA_LIST_SAGA: "GET_CINEMA_LIST_SAGA",
  CREATE_SCHEDULE_SAGA: "CREATE_SCHEDULE_SAGA",
  GET_SCHEDULE_BY_CINEMA_SAGA: "GET_SCHEDULE_BY_CINEMA_SAGA",

  // USER
  GET_USER_TYPE_LIST_SAGA: "GET_USER_TYPE_LIST_SAGA",
  GET_USER_LIST_SAGA: "GET_USER_LIST_SAGA",
  ADD_USER_SAGA: "ADD_USER_SAGA",
  EDIT_USER_SAGA: "EDIT_USER_SAGA",
  DELETE_USER_SAGA: "DELETE_USER_SAGA",
  GET_USER_DETAIL_SAGA: "GET_USER_DETAIL_SAGA",
};
